apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance
  labels:
    app: insurance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance-container
        image: iamajaygaur/insurance
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-np-service
  labels:
    app: insurance
spec:
  selector:
    app: insurance

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
